//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IOASDBEntities : DbContext
    {
        public IOASDBEntities()
            : base("name=IOASDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUserRole> tblUserRole { get; set; }
        public virtual DbSet<tblRoleaccess> tblRoleaccess { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblProformaInvoice> tblProformaInvoice { get; set; }
        public virtual DbSet<tblProformaInvoiceDraft> tblProformaInvoiceDraft { get; set; }
        public virtual DbSet<tblProformaInvoiceTaxDetails> tblProformaInvoiceTaxDetails { get; set; }
        public virtual DbSet<tblProject> tblProject { get; set; }
        public virtual DbSet<tblProjectInvoice> tblProjectInvoice { get; set; }
        public virtual DbSet<tblProjectInvoiceDraft> tblProjectInvoiceDraft { get; set; }
        public virtual DbSet<tblInvoiceTaxDetails> tblInvoiceTaxDetails { get; set; }
        public virtual DbSet<tblLoginDetails> tblLoginDetails { get; set; }
        public virtual DbSet<tblAccountGroup> tblAccountGroup { get; set; }
        public virtual DbSet<tblAccountHead> tblAccountHead { get; set; }
        public virtual DbSet<tblAccountType> tblAccountType { get; set; }
        public virtual DbSet<tblAdhocPayCheckDetail> tblAdhocPayCheckDetail { get; set; }
        public virtual DbSet<tblAdhocPayCommitmentDetail> tblAdhocPayCommitmentDetail { get; set; }
        public virtual DbSet<tblAdhocPayDeductionDetail> tblAdhocPayDeductionDetail { get; set; }
        public virtual DbSet<tblAdhocPayDocumentDetail> tblAdhocPayDocumentDetail { get; set; }
        public virtual DbSet<tblAdhocPayExpenseDetail> tblAdhocPayExpenseDetail { get; set; }
        public virtual DbSet<tblAdhocPayInvoiceDetails> tblAdhocPayInvoiceDetails { get; set; }
        public virtual DbSet<tblAdhocPayment> tblAdhocPayment { get; set; }
        public virtual DbSet<tblAdhocSalaryBreakUpDetail> tblAdhocSalaryBreakUpDetail { get; set; }
        public virtual DbSet<tblAdhocSalaryCommitmentDetail> tblAdhocSalaryCommitmentDetail { get; set; }
        public virtual DbSet<tblAdhocSalaryOtherAllowance> tblAdhocSalaryOtherAllowance { get; set; }
        public virtual DbSet<tblAgencyDocument> tblAgencyDocument { get; set; }
        public virtual DbSet<tblAgencyMaster> tblAgencyMaster { get; set; }
        public virtual DbSet<tblAgencySalary> tblAgencySalary { get; set; }
        public virtual DbSet<tblAgencySalaryBreakUpDetail> tblAgencySalaryBreakUpDetail { get; set; }
        public virtual DbSet<tblAgencySalaryCheckDetail> tblAgencySalaryCheckDetail { get; set; }
        public virtual DbSet<tblAgencySalaryCommitmentDetail> tblAgencySalaryCommitmentDetail { get; set; }
        public virtual DbSet<tblAgencySalaryDeductionDetail> tblAgencySalaryDeductionDetail { get; set; }
        public virtual DbSet<tblAgencySalaryDocumentDetail> tblAgencySalaryDocumentDetail { get; set; }
        public virtual DbSet<tblAgencySalaryOtherAllowance> tblAgencySalaryOtherAllowance { get; set; }
        public virtual DbSet<tblAgencySalaryTransactionDetail> tblAgencySalaryTransactionDetail { get; set; }
        public virtual DbSet<tblAgencyVerifiedSalary> tblAgencyVerifiedSalary { get; set; }
        public virtual DbSet<tblBankAccountMapping> tblBankAccountMapping { get; set; }
        public virtual DbSet<tblBankAccountMaster> tblBankAccountMaster { get; set; }
        public virtual DbSet<tblBankProjectGroup> tblBankProjectGroup { get; set; }
        public virtual DbSet<tblBillCheckDetail> tblBillCheckDetail { get; set; }
        public virtual DbSet<tblBillCommitmentDetail> tblBillCommitmentDetail { get; set; }
        public virtual DbSet<tblBillDeductionDetail> tblBillDeductionDetail { get; set; }
        public virtual DbSet<tblBillDocumentDetail> tblBillDocumentDetail { get; set; }
        public virtual DbSet<tblBillEntry> tblBillEntry { get; set; }
        public virtual DbSet<tblBillExpenseDetail> tblBillExpenseDetail { get; set; }
        public virtual DbSet<tblBillPaymentTransactionDetail> tblBillPaymentTransactionDetail { get; set; }
        public virtual DbSet<tblBillPODetail> tblBillPODetail { get; set; }
        public virtual DbSet<tblBillTDSDetail> tblBillTDSDetail { get; set; }
        public virtual DbSet<tblBOA> tblBOA { get; set; }
        public virtual DbSet<tblBOADetail> tblBOADetail { get; set; }
        public virtual DbSet<tblBOADraft> tblBOADraft { get; set; }
        public virtual DbSet<tblBOADraftDetail> tblBOADraftDetail { get; set; }
        public virtual DbSet<tblBOAPaymentDetail> tblBOAPaymentDetail { get; set; }
        public virtual DbSet<tblBOASubTransaction> tblBOASubTransaction { get; set; }
        public virtual DbSet<tblBOASummary> tblBOASummary { get; set; }
        public virtual DbSet<tblBOATransaction> tblBOATransaction { get; set; }
        public virtual DbSet<tblBRS> tblBRS { get; set; }
        public virtual DbSet<tblBRSBOADetail> tblBRSBOADetail { get; set; }
        public virtual DbSet<tblBRSDetail> tblBRSDetail { get; set; }
        public virtual DbSet<tblBudgetHead> tblBudgetHead { get; set; }
        public virtual DbSet<tblCardDocumentDetail> tblCardDocumentDetail { get; set; }
        public virtual DbSet<tblCategoryType> tblCategoryType { get; set; }
        public virtual DbSet<tblClearanceAgentMaster> tblClearanceAgentMaster { get; set; }
        public virtual DbSet<tblClearanceAgentTDSDetail> tblClearanceAgentTDSDetail { get; set; }
        public virtual DbSet<tblClearancePaymentBreakUpDetail> tblClearancePaymentBreakUpDetail { get; set; }
        public virtual DbSet<tblClearancePaymentCheckDetail> tblClearancePaymentCheckDetail { get; set; }
        public virtual DbSet<tblClearancePaymentCommitmentDetail> tblClearancePaymentCommitmentDetail { get; set; }
        public virtual DbSet<tblClearancePaymentDeductionDetail> tblClearancePaymentDeductionDetail { get; set; }
        public virtual DbSet<tblClearancePaymentDocumentDetail> tblClearancePaymentDocumentDetail { get; set; }
        public virtual DbSet<tblClearancePaymentEntry> tblClearancePaymentEntry { get; set; }
        public virtual DbSet<tblClearancePaymentExpenseDetail> tblClearancePaymentExpenseDetail { get; set; }
        public virtual DbSet<tblClearancePaymentInvoiceDetail> tblClearancePaymentInvoiceDetail { get; set; }
        public virtual DbSet<tblClearancePaymentPODetail> tblClearancePaymentPODetail { get; set; }
        public virtual DbSet<tblClearancePaymentTDSDetail> tblClearancePaymentTDSDetail { get; set; }
        public virtual DbSet<tblClearancePaymentTransactionDetail> tblClearancePaymentTransactionDetail { get; set; }
        public virtual DbSet<tblCodeControl> tblCodeControl { get; set; }
        public virtual DbSet<tblCommitment> tblCommitment { get; set; }
        public virtual DbSet<tblCommitmentClosedLog> tblCommitmentClosedLog { get; set; }
        public virtual DbSet<tblCommitmentDetails> tblCommitmentDetails { get; set; }
        public virtual DbSet<tblCommitmentLog> tblCommitmentLog { get; set; }
        public virtual DbSet<tblCommonHeads> tblCommonHeads { get; set; }
        public virtual DbSet<tblConsultancyFundingCategory> tblConsultancyFundingCategory { get; set; }
        public virtual DbSet<tblContra> tblContra { get; set; }
        public virtual DbSet<tblContraDetail> tblContraDetail { get; set; }
        public virtual DbSet<tblCountries> tblCountries { get; set; }
        public virtual DbSet<tblCreditNote> tblCreditNote { get; set; }
        public virtual DbSet<tblCurrency> tblCurrency { get; set; }
        public virtual DbSet<tblDDFMapping> tblDDFMapping { get; set; }
        public virtual DbSet<tblDeductionHead> tblDeductionHead { get; set; }
        public virtual DbSet<tblDepartment> tblDepartment { get; set; }
        public virtual DbSet<tblDistributeInstituteOHBreakup> tblDistributeInstituteOHBreakup { get; set; }
        public virtual DbSet<tblDistribution> tblDistribution { get; set; }
        public virtual DbSet<tblDistributionCheckDetail> tblDistributionCheckDetail { get; set; }
        public virtual DbSet<tblDistributionCommitmentDetail> tblDistributionCommitmentDetail { get; set; }
        public virtual DbSet<tblDistributionDeductionDetail> tblDistributionDeductionDetail { get; set; }
        public virtual DbSet<tblDistributionDetails> tblDistributionDetails { get; set; }
        public virtual DbSet<tblDistributionDocumentDetail> tblDistributionDocumentDetail { get; set; }
        public virtual DbSet<tblDistributionExpenseDetail> tblDistributionExpenseDetail { get; set; }
        public virtual DbSet<tblDistributionOHPDeductionDetail> tblDistributionOHPDeductionDetail { get; set; }
        public virtual DbSet<tblDistributionOHPDetails> tblDistributionOHPDetails { get; set; }
        public virtual DbSet<tblDistributionOHPExpenseDetail> tblDistributionOHPExpenseDetail { get; set; }
        public virtual DbSet<tblDistributionPCFDetails> tblDistributionPCFDetails { get; set; }
        public virtual DbSet<tblDocument> tblDocument { get; set; }
        public virtual DbSet<tblDynamicReports> tblDynamicReports { get; set; }
        public virtual DbSet<tblEmpITDeclaration> tblEmpITDeclaration { get; set; }
        public virtual DbSet<tblEmpITDeclarationDoc> tblEmpITDeclarationDoc { get; set; }
        public virtual DbSet<tblEmployeePCFAccountDetails> tblEmployeePCFAccountDetails { get; set; }
        public virtual DbSet<tblEmpOtherAllowance> tblEmpOtherAllowance { get; set; }
        public virtual DbSet<tblEmpOtherDeduction> tblEmpOtherDeduction { get; set; }
        public virtual DbSet<tblEmpOtherIncome> tblEmpOtherIncome { get; set; }
        public virtual DbSet<tblEmpSOPIncome> tblEmpSOPIncome { get; set; }
        public virtual DbSet<tblEvent> tblEvent { get; set; }
        public virtual DbSet<tblFacultyDetail> tblFacultyDetail { get; set; }
        public virtual DbSet<tblFellowShip> tblFellowShip { get; set; }
        public virtual DbSet<tblFellowShipChangeLog> tblFellowShipChangeLog { get; set; }
        public virtual DbSet<tblFellowshipSalary> tblFellowshipSalary { get; set; }
        public virtual DbSet<tblFellowshipSalaryCheckDetail> tblFellowshipSalaryCheckDetail { get; set; }
        public virtual DbSet<tblFellowshipSalaryDetails> tblFellowshipSalaryDetails { get; set; }
        public virtual DbSet<tblFellowshipSalaryDocumentDetail> tblFellowshipSalaryDocumentDetail { get; set; }
        public virtual DbSet<tblFellowshipSalaryExpenseDetail> tblFellowshipSalaryExpenseDetail { get; set; }
        public virtual DbSet<tblFinYear> tblFinYear { get; set; }
        public virtual DbSet<tblForeignRemitCheckDetail> tblForeignRemitCheckDetail { get; set; }
        public virtual DbSet<tblForeignRemitCommitmentDetail> tblForeignRemitCommitmentDetail { get; set; }
        public virtual DbSet<tblForeignRemitDeductionDetail> tblForeignRemitDeductionDetail { get; set; }
        public virtual DbSet<tblForeignRemitDocumentDetail> tblForeignRemitDocumentDetail { get; set; }
        public virtual DbSet<tblForeignRemitExpenseDetail> tblForeignRemitExpenseDetail { get; set; }
        public virtual DbSet<tblForeignRemittance> tblForeignRemittance { get; set; }
        public virtual DbSet<tblFunction> tblFunction { get; set; }
        public virtual DbSet<tblFunctionCheckList> tblFunctionCheckList { get; set; }
        public virtual DbSet<tblFunctionDocument> tblFunctionDocument { get; set; }
        public virtual DbSet<tblFunctionStatus> tblFunctionStatus { get; set; }
        public virtual DbSet<tblGeneralVoucher> tblGeneralVoucher { get; set; }
        public virtual DbSet<tblGeneralVoucherCommitmentDetail> tblGeneralVoucherCommitmentDetail { get; set; }
        public virtual DbSet<tblGeneralVoucherDeductionDetail> tblGeneralVoucherDeductionDetail { get; set; }
        public virtual DbSet<tblGeneralVoucherExpenseDetail> tblGeneralVoucherExpenseDetail { get; set; }
        public virtual DbSet<tblGeneralVoucherPaymentBreakUpDetail> tblGeneralVoucherPaymentBreakUpDetail { get; set; }
        public virtual DbSet<tblGroupMapping> tblGroupMapping { get; set; }
        public virtual DbSet<tblGSTBalanceSummary> tblGSTBalanceSummary { get; set; }
        public virtual DbSet<tblGstDocument> tblGstDocument { get; set; }
        public virtual DbSet<tblGSTMonthlySplitup> tblGSTMonthlySplitup { get; set; }
        public virtual DbSet<tblGSTOffset> tblGSTOffset { get; set; }
        public virtual DbSet<tblGSTOffsetdetails> tblGSTOffsetdetails { get; set; }
        public virtual DbSet<tblGSTOffsetExpenseDetail> tblGSTOffsetExpenseDetail { get; set; }
        public virtual DbSet<tblHeadOBDeletedLog> tblHeadOBDeletedLog { get; set; }
        public virtual DbSet<tblHeadOpeningBalance> tblHeadOpeningBalance { get; set; }
        public virtual DbSet<tblHonororium> tblHonororium { get; set; }
        public virtual DbSet<tblHonororiumCheckDetail> tblHonororiumCheckDetail { get; set; }
        public virtual DbSet<tblHonororiumCommitmentDetail> tblHonororiumCommitmentDetail { get; set; }
        public virtual DbSet<tblHonororiumDeductionDetail> tblHonororiumDeductionDetail { get; set; }
        public virtual DbSet<tblHonororiumDetails> tblHonororiumDetails { get; set; }
        public virtual DbSet<tblHonororiumDocumentDetail> tblHonororiumDocumentDetail { get; set; }
        public virtual DbSet<tblHonororiumExpenseDetail> tblHonororiumExpenseDetail { get; set; }
        public virtual DbSet<tblHonororiumPCFDetail> tblHonororiumPCFDetail { get; set; }
        public virtual DbSet<tblIITMBankMaster> tblIITMBankMaster { get; set; }
        public virtual DbSet<tblImportPaymentBankMapping> tblImportPaymentBankMapping { get; set; }
        public virtual DbSet<tblImpRecoupCommitmentDetail> tblImpRecoupCommitmentDetail { get; set; }
        public virtual DbSet<tblImprestBillRecoupDetail> tblImprestBillRecoupDetail { get; set; }
        public virtual DbSet<tblImprestBillRecoupment> tblImprestBillRecoupment { get; set; }
        public virtual DbSet<tblImprestCheckDetail> tblImprestCheckDetail { get; set; }
        public virtual DbSet<tblImprestDeductionDetail> tblImprestDeductionDetail { get; set; }
        public virtual DbSet<tblImprestDocumentDetail> tblImprestDocumentDetail { get; set; }
        public virtual DbSet<tblImprestExpenseDetail> tblImprestExpenseDetail { get; set; }
        public virtual DbSet<tblImprestPaymentDetails> tblImprestPaymentDetails { get; set; }
        public virtual DbSet<tblImprestRecoupBillBreakup> tblImprestRecoupBillBreakup { get; set; }
        public virtual DbSet<tblImprestRecoupCheckDetail> tblImprestRecoupCheckDetail { get; set; }
        public virtual DbSet<tblImprestRecoupDeductionDetail> tblImprestRecoupDeductionDetail { get; set; }
        public virtual DbSet<tblImprestRecoupExpenseDetail> tblImprestRecoupExpenseDetail { get; set; }
        public virtual DbSet<tblImprestRecoupment> tblImprestRecoupment { get; set; }
        public virtual DbSet<tblIMPUserDetails> tblIMPUserDetails { get; set; }
        public virtual DbSet<tblIMPUserEntryCommitmentDetail> tblIMPUserEntryCommitmentDetail { get; set; }
        public virtual DbSet<tblInstallment> tblInstallment { get; set; }
        public virtual DbSet<tblInstituteClaims> tblInstituteClaims { get; set; }
        public virtual DbSet<tblInstituteClaimsExpenseDetail> tblInstituteClaimsExpenseDetail { get; set; }
        public virtual DbSet<tblInstituteMaster> tblInstituteMaster { get; set; }
        public virtual DbSet<tblInstituteSalaryPayment> tblInstituteSalaryPayment { get; set; }
        public virtual DbSet<tblInstituteSalaryPaymentCheckDetail> tblInstituteSalaryPaymentCheckDetail { get; set; }
        public virtual DbSet<tblInstituteSalaryPaymentDeductionDetail> tblInstituteSalaryPaymentDeductionDetail { get; set; }
        public virtual DbSet<tblInstituteSalaryPaymentDetails> tblInstituteSalaryPaymentDetails { get; set; }
        public virtual DbSet<tblInstituteSalaryPaymentDocumentDetail> tblInstituteSalaryPaymentDocumentDetail { get; set; }
        public virtual DbSet<tblInstituteSalaryPaymentExpenseDetail> tblInstituteSalaryPaymentExpenseDetail { get; set; }
        public virtual DbSet<tblInvoiceOpeningReceipts> tblInvoiceOpeningReceipts { get; set; }
        public virtual DbSet<tblITDeclaration> tblITDeclaration { get; set; }
        public virtual DbSet<tblJointDevelopmentCompany> tblJointDevelopmentCompany { get; set; }
        public virtual DbSet<tblJournal> tblJournal { get; set; }
        public virtual DbSet<tblJournalDocumentDetail> tblJournalDocumentDetail { get; set; }
        public virtual DbSet<tblJournalTransationDetail> tblJournalTransationDetail { get; set; }
        public virtual DbSet<tblLCAmmendCheckDetail> tblLCAmmendCheckDetail { get; set; }
        public virtual DbSet<tblLCAmmendment> tblLCAmmendment { get; set; }
        public virtual DbSet<tblLCAmmendmentClause> tblLCAmmendmentClause { get; set; }
        public virtual DbSet<tblLCAmmendmentCommitmentDetail> tblLCAmmendmentCommitmentDetail { get; set; }
        public virtual DbSet<tblLCAmmendmentDeductionDetail> tblLCAmmendmentDeductionDetail { get; set; }
        public virtual DbSet<tblLCAmmendmentDocument> tblLCAmmendmentDocument { get; set; }
        public virtual DbSet<tblLCAmmendmentExpenseDetail> tblLCAmmendmentExpenseDetail { get; set; }
        public virtual DbSet<tblLCCommitmentDetail> tblLCCommitmentDetail { get; set; }
        public virtual DbSet<tblLCDocumentInfo> tblLCDocumentInfo { get; set; }
        public virtual DbSet<tblLCDraftAdditionalConditions> tblLCDraftAdditionalConditions { get; set; }
        public virtual DbSet<tblLCDraftCheckDetail> tblLCDraftCheckDetail { get; set; }
        public virtual DbSet<tblLCDraftDeductionDetail> tblLCDraftDeductionDetail { get; set; }
        public virtual DbSet<tblLCDraftDetails> tblLCDraftDetails { get; set; }
        public virtual DbSet<tblLCDraftDocument> tblLCDraftDocument { get; set; }
        public virtual DbSet<tblLCDraftExpenseDetail> tblLCDraftExpenseDetail { get; set; }
        public virtual DbSet<tblLCDraftOpeningClause> tblLCDraftOpeningClause { get; set; }
        public virtual DbSet<tblLCDraftPaymentTerms> tblLCDraftPaymentTerms { get; set; }
        public virtual DbSet<tblLCRetireCheckDetail> tblLCRetireCheckDetail { get; set; }
        public virtual DbSet<tblLCRetirement> tblLCRetirement { get; set; }
        public virtual DbSet<tblLCRetirementCheckDetail> tblLCRetirementCheckDetail { get; set; }
        public virtual DbSet<tblLCRetirementCommitmentDetail> tblLCRetirementCommitmentDetail { get; set; }
        public virtual DbSet<tblLCRetirementDeductionDetail> tblLCRetirementDeductionDetail { get; set; }
        public virtual DbSet<tblLCRetirementDeducts> tblLCRetirementDeducts { get; set; }
        public virtual DbSet<tblLCRetirementDocument> tblLCRetirementDocument { get; set; }
        public virtual DbSet<tblLCRetirementExpenseDetail> tblLCRetirementExpenseDetail { get; set; }
        public virtual DbSet<tblManDay> tblManDay { get; set; }
        public virtual DbSet<tblManDayCheckDetail> tblManDayCheckDetail { get; set; }
        public virtual DbSet<tblManDayCommitmentDetail> tblManDayCommitmentDetail { get; set; }
        public virtual DbSet<tblManDayDeductionDetail> tblManDayDeductionDetail { get; set; }
        public virtual DbSet<tblManDayDetails> tblManDayDetails { get; set; }
        public virtual DbSet<tblManDayDocumentDetail> tblManDayDocumentDetail { get; set; }
        public virtual DbSet<tblManDayExpenseDetail> tblManDayExpenseDetail { get; set; }
        public virtual DbSet<tblMenuGroup> tblMenuGroup { get; set; }
        public virtual DbSet<tblMinistryMaster> tblMinistryMaster { get; set; }
        public virtual DbSet<tblModules> tblModules { get; set; }
        public virtual DbSet<tblNegativeBalance> tblNegativeBalance { get; set; }
        public virtual DbSet<tblNotification> tblNotification { get; set; }
        public virtual DbSet<tblOfficeOrder> tblOfficeOrder { get; set; }
        public virtual DbSet<tblOfficeOrderDetail> tblOfficeOrderDetail { get; set; }
        public virtual DbSet<tblOtherInstituteCoPI> tblOtherInstituteCoPI { get; set; }
        public virtual DbSet<tblOtherPayment> tblOtherPayment { get; set; }
        public virtual DbSet<tblOverheadsPercentage> tblOverheadsPercentage { get; set; }
        public virtual DbSet<tblOverheadsPosting> tblOverheadsPosting { get; set; }
        public virtual DbSet<tblOverheadsPostingContraDetail> tblOverheadsPostingContraDetail { get; set; }
        public virtual DbSet<tblOverheadsPostingCorpusDetails> tblOverheadsPostingCorpusDetails { get; set; }
        public virtual DbSet<tblOverheadsPostingDDFDetails> tblOverheadsPostingDDFDetails { get; set; }
        public virtual DbSet<tblOverheadsPostingDeductionDetail> tblOverheadsPostingDeductionDetail { get; set; }
        public virtual DbSet<tblOverheadsPostingDetails> tblOverheadsPostingDetails { get; set; }
        public virtual DbSet<tblOverheadsPostingExpenseDetail> tblOverheadsPostingExpenseDetail { get; set; }
        public virtual DbSet<tblOverheadsPostingICSROHDetails> tblOverheadsPostingICSROHDetails { get; set; }
        public virtual DbSet<tblOverheadsPostingPCFDetails> tblOverheadsPostingPCFDetails { get; set; }
        public virtual DbSet<tblOverheadsPostingRMFDetails> tblOverheadsPostingRMFDetails { get; set; }
        public virtual DbSet<tblOverheadsPostingSWFDetails> tblOverheadsPostingSWFDetails { get; set; }
        public virtual DbSet<tblPartTimePayment> tblPartTimePayment { get; set; }
        public virtual DbSet<tblPartTimePaymentCheckDetail> tblPartTimePaymentCheckDetail { get; set; }
        public virtual DbSet<tblPartTimePaymentCommitmentDetail> tblPartTimePaymentCommitmentDetail { get; set; }
        public virtual DbSet<tblPartTimePaymentDeductionDetail> tblPartTimePaymentDeductionDetail { get; set; }
        public virtual DbSet<tblPartTimePaymentDocumentDetail> tblPartTimePaymentDocumentDetail { get; set; }
        public virtual DbSet<tblPartTimePaymentExpenseDetail> tblPartTimePaymentExpenseDetail { get; set; }
        public virtual DbSet<tblPartTimeStudentDetails> tblPartTimeStudentDetails { get; set; }
        public virtual DbSet<tblPayment> tblPayment { get; set; }
        public virtual DbSet<tblPaymentPayee> tblPaymentPayee { get; set; }
        public virtual DbSet<tblPaymentTransaction> tblPaymentTransaction { get; set; }
        public virtual DbSet<tblPCFDistribution> tblPCFDistribution { get; set; }
        public virtual DbSet<tblPCFDistributionOtherPosting> tblPCFDistributionOtherPosting { get; set; }
        public virtual DbSet<tblPCFDistributionPCFDetails> tblPCFDistributionPCFDetails { get; set; }
        public virtual DbSet<tblPCFRMFShareLog> tblPCFRMFShareLog { get; set; }
        public virtual DbSet<tblProcessGuidelineDetail> tblProcessGuidelineDetail { get; set; }
        public virtual DbSet<tblProcessGuidelineDocument> tblProcessGuidelineDocument { get; set; }
        public virtual DbSet<tblProcessGuidelineHeader> tblProcessGuidelineHeader { get; set; }
        public virtual DbSet<tblProcessGuidelineUser> tblProcessGuidelineUser { get; set; }
        public virtual DbSet<tblProcessGuidelineWorkFlow> tblProcessGuidelineWorkFlow { get; set; }
        public virtual DbSet<tblProcessGuidelineWorkflowDocument> tblProcessGuidelineWorkflowDocument { get; set; }
        public virtual DbSet<tblProcessTransaction> tblProcessTransaction { get; set; }
        public virtual DbSet<tblProcessTransactionDetail> tblProcessTransactionDetail { get; set; }
        public virtual DbSet<tblProcessTransactionDocuments> tblProcessTransactionDocuments { get; set; }
        public virtual DbSet<tblProjectAllocation> tblProjectAllocation { get; set; }
        public virtual DbSet<tblProjectCoPI> tblProjectCoPI { get; set; }
        public virtual DbSet<tblProjectDirectTransfer> tblProjectDirectTransfer { get; set; }
        public virtual DbSet<tblProjectEnhancement> tblProjectEnhancement { get; set; }
        public virtual DbSet<tblProjectEnhancementAllocation> tblProjectEnhancementAllocation { get; set; }
        public virtual DbSet<tblProjectFundingBody> tblProjectFundingBody { get; set; }
        public virtual DbSet<tblProjectOB> tblProjectOB { get; set; }
        public virtual DbSet<tblProjectOBDetail> tblProjectOBDetail { get; set; }
        public virtual DbSet<tblProjectOtherInstituteCoPI> tblProjectOtherInstituteCoPI { get; set; }
        public virtual DbSet<tblProjectStaffCategoryMaster> tblProjectStaffCategoryMaster { get; set; }
        public virtual DbSet<tblProjectStaffCategorywiseBreakup> tblProjectStaffCategorywiseBreakup { get; set; }
        public virtual DbSet<tblProjectStaffDetail> tblProjectStaffDetail { get; set; }
        public virtual DbSet<tblProjectStatusLog> tblProjectStatusLog { get; set; }
        public virtual DbSet<tblProjectTransactionlog> tblProjectTransactionlog { get; set; }
        public virtual DbSet<tblProjectTransCommitmentDetail> tblProjectTransCommitmentDetail { get; set; }
        public virtual DbSet<tblProjectTransfer> tblProjectTransfer { get; set; }
        public virtual DbSet<tblProjectTransferDetails> tblProjectTransferDetails { get; set; }
        public virtual DbSet<tblProposal> tblProposal { get; set; }
        public virtual DbSet<tblProposalCoPI> tblProposalCoPI { get; set; }
        public virtual DbSet<tblProposalSupportDocuments> tblProposalSupportDocuments { get; set; }
        public virtual DbSet<tblReceipt> tblReceipt { get; set; }
        public virtual DbSet<tblReceiptAgencyShareDetails> tblReceiptAgencyShareDetails { get; set; }
        public virtual DbSet<tblReceiptAllocation> tblReceiptAllocation { get; set; }
        public virtual DbSet<tblReceiptClaim> tblReceiptClaim { get; set; }
        public virtual DbSet<tblReceiptClaimsdetail> tblReceiptClaimsdetail { get; set; }
        public virtual DbSet<tblReceiptClaimsExpenseDetail> tblReceiptClaimsExpenseDetail { get; set; }
        public virtual DbSet<tblReceiptOverheadBreakup> tblReceiptOverheadBreakup { get; set; }
        public virtual DbSet<tblReceiptRecivables> tblReceiptRecivables { get; set; }
        public virtual DbSet<tblReceiptTransactionDetails> tblReceiptTransactionDetails { get; set; }
        public virtual DbSet<tblReversedCommitmentLog> tblReversedCommitmentLog { get; set; }
        public virtual DbSet<tblReverseTaxDocument> tblReverseTaxDocument { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
        public virtual DbSet<tblSalaryAgencyMaster> tblSalaryAgencyMaster { get; set; }
        public virtual DbSet<tblSalaryHead> tblSalaryHead { get; set; }
        public virtual DbSet<tblSalaryPayment> tblSalaryPayment { get; set; }
        public virtual DbSet<tblSalaryPaymentHead> tblSalaryPaymentHead { get; set; }
        public virtual DbSet<tblSalaryTransaction> tblSalaryTransaction { get; set; }
        public virtual DbSet<tblSalaryTransactionDetail> tblSalaryTransactionDetail { get; set; }
        public virtual DbSet<tblSBICardCheckDetail> tblSBICardCheckDetail { get; set; }
        public virtual DbSet<tblSBICardEntryExpenseDetail> tblSBICardEntryExpenseDetail { get; set; }
        public virtual DbSet<tblSBICardRecoupCheckDetail> tblSBICardRecoupCheckDetail { get; set; }
        public virtual DbSet<tblSBICardRecoupExpenseDetail> tblSBICardRecoupExpenseDetail { get; set; }
        public virtual DbSet<tblSBICardRecoupment> tblSBICardRecoupment { get; set; }
        public virtual DbSet<tblSBIEcardDeductionDetail> tblSBIEcardDeductionDetail { get; set; }
        public virtual DbSet<tblSBIECardDetails> tblSBIECardDetails { get; set; }
        public virtual DbSet<tblSBIECardDocumentDetail> tblSBIECardDocumentDetail { get; set; }
        public virtual DbSet<tblSBIECardEntryCommitmentDetail> tblSBIECardEntryCommitmentDetail { get; set; }
        public virtual DbSet<tblSBIECardPrjctCommitmentDetail> tblSBIECardPrjctCommitmentDetail { get; set; }
        public virtual DbSet<tblSBIEcardRecoupBillBreakup> tblSBIEcardRecoupBillBreakup { get; set; }
        public virtual DbSet<tblSBIEcardRecoupDeductionDetail> tblSBIEcardRecoupDeductionDetail { get; set; }
        public virtual DbSet<tblSBIPrepaidCardProjectDetails> tblSBIPrepaidCardProjectDetails { get; set; }
        public virtual DbSet<tblSchemes> tblSchemes { get; set; }
        public virtual DbSet<tblSponsoredSchemes> tblSponsoredSchemes { get; set; }
        public virtual DbSet<tblSRB> tblSRB { get; set; }
        public virtual DbSet<tblSRBDeactivation> tblSRBDeactivation { get; set; }
        public virtual DbSet<tblSRBDetails> tblSRBDetails { get; set; }
        public virtual DbSet<tblSRBItemCategory> tblSRBItemCategory { get; set; }
        public virtual DbSet<tblStaffAppointmentExtension> tblStaffAppointmentExtension { get; set; }
        public virtual DbSet<tblStaffAppointmentMaster> tblStaffAppointmentMaster { get; set; }
        public virtual DbSet<tblStaffDetail> tblStaffDetail { get; set; }
        public virtual DbSet<tblStateMaster> tblStateMaster { get; set; }
        public virtual DbSet<tblStudentDetail> tblStudentDetail { get; set; }
        public virtual DbSet<tblSummerInternshipCheckDetail> tblSummerInternshipCheckDetail { get; set; }
        public virtual DbSet<tblSummerInternshipDocumentDetail> tblSummerInternshipDocumentDetail { get; set; }
        public virtual DbSet<tblSummerInternshipExpenseDetail> tblSummerInternshipExpenseDetail { get; set; }
        public virtual DbSet<tblSummerInternshipStudentDetails> tblSummerInternshipStudentDetails { get; set; }
        public virtual DbSet<tblSummrInternCommitmentDetail> tblSummrInternCommitmentDetail { get; set; }
        public virtual DbSet<tblSummrInternDeductionDetail> tblSummrInternDeductionDetail { get; set; }
        public virtual DbSet<tblSupportDocuments> tblSupportDocuments { get; set; }
        public virtual DbSet<tblTapal> tblTapal { get; set; }
        public virtual DbSet<tblTapalDocumentDetail> tblTapalDocumentDetail { get; set; }
        public virtual DbSet<tblTapalWorkflow> tblTapalWorkflow { get; set; }
        public virtual DbSet<tblTaxDetails> tblTaxDetails { get; set; }
        public virtual DbSet<tblTaxMaster> tblTaxMaster { get; set; }
        public virtual DbSet<tblTaxSlab> tblTaxSlab { get; set; }
        public virtual DbSet<tblTDSDocument> tblTDSDocument { get; set; }
        public virtual DbSet<tblTDSGSTDetails> tblTDSGSTDetails { get; set; }
        public virtual DbSet<tblTDSIncomeTaxDetails> tblTDSIncomeTaxDetails { get; set; }
        public virtual DbSet<tblTDSMaster> tblTDSMaster { get; set; }
        public virtual DbSet<tblTDSPayment> tblTDSPayment { get; set; }
        public virtual DbSet<tblTempAdvanceBreakUpDetail> tblTempAdvanceBreakUpDetail { get; set; }
        public virtual DbSet<tblTempAdvanceSettlement> tblTempAdvanceSettlement { get; set; }
        public virtual DbSet<tblTempAdvCheckDetail> tblTempAdvCheckDetail { get; set; }
        public virtual DbSet<tblTempAdvCommitmentDetail> tblTempAdvCommitmentDetail { get; set; }
        public virtual DbSet<tblTempAdvDeductionDetail> tblTempAdvDeductionDetail { get; set; }
        public virtual DbSet<tblTempAdvExpenseDetail> tblTempAdvExpenseDetail { get; set; }
        public virtual DbSet<tblTempAdvSettlCheckDetail> tblTempAdvSettlCheckDetail { get; set; }
        public virtual DbSet<tblTempAdvSettlCommitmentDetail> tblTempAdvSettlCommitmentDetail { get; set; }
        public virtual DbSet<tblTempAdvSettlDeductionDetail> tblTempAdvSettlDeductionDetail { get; set; }
        public virtual DbSet<tblTempAdvSettlementBillBreakup> tblTempAdvSettlementBillBreakup { get; set; }
        public virtual DbSet<tblTempAdvSettlExpenseDetail> tblTempAdvSettlExpenseDetail { get; set; }
        public virtual DbSet<tblTemporaryAdvance> tblTemporaryAdvance { get; set; }
        public virtual DbSet<tblTemporaryAdvanceDocumentDetail> tblTemporaryAdvanceDocumentDetail { get; set; }
        public virtual DbSet<tblTemporaryAdvanceSettlementBill> tblTemporaryAdvanceSettlementBill { get; set; }
        public virtual DbSet<tblTransactionDefinition> tblTransactionDefinition { get; set; }
        public virtual DbSet<tblTransactionTypeCode> tblTransactionTypeCode { get; set; }
        public virtual DbSet<tblTravelBill> tblTravelBill { get; set; }
        public virtual DbSet<tblTravelBillBreakUpDetail> tblTravelBillBreakUpDetail { get; set; }
        public virtual DbSet<tblTravelBillCheckDetail> tblTravelBillCheckDetail { get; set; }
        public virtual DbSet<tblTravelBillCommitmentDetail> tblTravelBillCommitmentDetail { get; set; }
        public virtual DbSet<tblTravelBillDeductionDetail> tblTravelBillDeductionDetail { get; set; }
        public virtual DbSet<tblTravelBillDetail> tblTravelBillDetail { get; set; }
        public virtual DbSet<tblTravelBillDocumentDetail> tblTravelBillDocumentDetail { get; set; }
        public virtual DbSet<tblTravelBillExpenseDetail> tblTravelBillExpenseDetail { get; set; }
        public virtual DbSet<tblTravelBillTravellerDetail> tblTravelBillTravellerDetail { get; set; }
        public virtual DbSet<tblTravelDailyAllowance> tblTravelDailyAllowance { get; set; }
        public virtual DbSet<tblTravelInvoiceDetail> tblTravelInvoiceDetail { get; set; }
        public virtual DbSet<tblTravelPaymentBreakUpDetail> tblTravelPaymentBreakUpDetail { get; set; }
        public virtual DbSet<tblUpdateLedgerOBLog> tblUpdateLedgerOBLog { get; set; }
        public virtual DbSet<tblVendorMaster> tblVendorMaster { get; set; }
        public virtual DbSet<tblVendorTDSDetail> tblVendorTDSDetail { get; set; }
        public virtual DbSet<tblVoucherDetails> tblVoucherDetails { get; set; }
        public virtual DbSet<tblVoucherHead> tblVoucherHead { get; set; }
        public virtual DbSet<tblDynamicFilter> tblDynamicFilter { get; set; }
        public virtual DbSet<tblDynamicReportRoles> tblDynamicReportRoles { get; set; }
        public virtual DbSet<tblTaxMasterInvoice> tblTaxMasterInvoice { get; set; }
        public virtual DbSet<vw_ApprovalProcessFlowDetails> vw_ApprovalProcessFlowDetails { get; set; }
        public virtual DbSet<vw_BOATransactionDetails> vw_BOATransactionDetails { get; set; }
        public virtual DbSet<vw_CanaraBankBulkDetails> vw_CanaraBankBulkDetails { get; set; }
        public virtual DbSet<vw_CashBookPayment> vw_CashBookPayment { get; set; }
        public virtual DbSet<vw_CashBookReceipt> vw_CashBookReceipt { get; set; }
        public virtual DbSet<vw_ClosedCommitment> vw_ClosedCommitment { get; set; }
        public virtual DbSet<vw_CommitmentReport> vw_CommitmentReport { get; set; }
        public virtual DbSet<vw_DemoLedgers> vw_DemoLedgers { get; set; }
        public virtual DbSet<vw_Distribution> vw_Distribution { get; set; }
        public virtual DbSet<vw_Fellowship> vw_Fellowship { get; set; }
        public virtual DbSet<vw_Honorarium> vw_Honorarium { get; set; }
        public virtual DbSet<vw_ManDays> vw_ManDays { get; set; }
        public virtual DbSet<vw_Postings> vw_Postings { get; set; }
        public virtual DbSet<vw_ProjectDetails> vw_ProjectDetails { get; set; }
        public virtual DbSet<vw_ProjectTransactionReport> vw_ProjectTransactionReport { get; set; }
        public virtual DbSet<vw_SubLedger> vw_SubLedger { get; set; }
        public virtual DbSet<vw_TDSDetails> vw_TDSDetails { get; set; }
        public virtual DbSet<vw_VendorMaster> vw_VendorMaster { get; set; }
        public virtual DbSet<vw_VoucherBatch> vw_VoucherBatch { get; set; }
        public virtual DbSet<vwAccountGroupinHeadwise> vwAccountGroupinHeadwise { get; set; }
        public virtual DbSet<vwAdhocEmployeeCategory> vwAdhocEmployeeCategory { get; set; }
        public virtual DbSet<VWAppointInfo> VWAppointInfo { get; set; }
        public virtual DbSet<vwAppointmentDetails> vwAppointmentDetails { get; set; }
        public virtual DbSet<vwAppointmentMaster> vwAppointmentMaster { get; set; }
        public virtual DbSet<vwAppointmentProject> vwAppointmentProject { get; set; }
        public virtual DbSet<vwClosedCommitment> vwClosedCommitment { get; set; }
        public virtual DbSet<vwCombineStaffDetails> vwCombineStaffDetails { get; set; }
        public virtual DbSet<vwCommitmentSpentBalance> vwCommitmentSpentBalance { get; set; }
        public virtual DbSet<vwFacultyStaffDetails> vwFacultyStaffDetails { get; set; }
        public virtual DbSet<VWOfficeTransactions> VWOfficeTransactions { get; set; }
        public virtual DbSet<VWOngoing> VWOngoing { get; set; }
        public virtual DbSet<vwPaymaster> vwPaymaster { get; set; }
        public virtual DbSet<vwPaytype> vwPaytype { get; set; }
        public virtual DbSet<vwPI> vwPI { get; set; }
        public virtual DbSet<vwProjectTransferBalance> vwProjectTransferBalance { get; set; }
        public virtual DbSet<vwSalaryDetails> vwSalaryDetails { get; set; }
        public virtual DbSet<vwSalaryMaster> vwSalaryMaster { get; set; }
        public virtual DbSet<vwSRBDetails> vwSRBDetails { get; set; }
        public virtual DbSet<vwStudentDetails> vwStudentDetails { get; set; }
        public virtual DbSet<vwTapalDetails> vwTapalDetails { get; set; }
    
        public virtual int DynamicReportsIU(ObjectParameter reportID, string reportName, string description, string tableName, string fields, string groupByFields, string orderByFields, Nullable<int> isActive, Nullable<int> userId, Nullable<int> roleId, Nullable<int> moduleId, Nullable<bool> isDeleted, Nullable<bool> canExport, Nullable<bool> toPdf, Nullable<bool> toExcel, ObjectParameter status)
        {
            var reportNameParameter = reportName != null ?
                new ObjectParameter("ReportName", reportName) :
                new ObjectParameter("ReportName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var fieldsParameter = fields != null ?
                new ObjectParameter("Fields", fields) :
                new ObjectParameter("Fields", typeof(string));
    
            var groupByFieldsParameter = groupByFields != null ?
                new ObjectParameter("GroupByFields", groupByFields) :
                new ObjectParameter("GroupByFields", typeof(string));
    
            var orderByFieldsParameter = orderByFields != null ?
                new ObjectParameter("OrderByFields", orderByFields) :
                new ObjectParameter("OrderByFields", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var moduleIdParameter = moduleId.HasValue ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(int));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var canExportParameter = canExport.HasValue ?
                new ObjectParameter("canExport", canExport) :
                new ObjectParameter("canExport", typeof(bool));
    
            var toPdfParameter = toPdf.HasValue ?
                new ObjectParameter("toPdf", toPdf) :
                new ObjectParameter("toPdf", typeof(bool));
    
            var toExcelParameter = toExcel.HasValue ?
                new ObjectParameter("toExcel", toExcel) :
                new ObjectParameter("toExcel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DynamicReportsIU", reportID, reportNameParameter, descriptionParameter, tableNameParameter, fieldsParameter, groupByFieldsParameter, orderByFieldsParameter, isActiveParameter, userIdParameter, roleIdParameter, moduleIdParameter, isDeletedParameter, canExportParameter, toPdfParameter, toExcelParameter, status);
        }
    
        public virtual ObjectResult<GetDynamicReport_Result> GetDynamicReport(Nullable<int> reportID)
        {
            var reportIDParameter = reportID.HasValue ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDynamicReport_Result>("GetDynamicReport", reportIDParameter);
        }
    
        public virtual ObjectResult<GetDynamicReportByUser_Result> GetDynamicReportByUser(Nullable<int> reportID, string user, string reportName)
        {
            var reportIDParameter = reportID.HasValue ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var reportNameParameter = reportName != null ?
                new ObjectParameter("ReportName", reportName) :
                new ObjectParameter("ReportName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDynamicReportByUser_Result>("GetDynamicReportByUser", reportIDParameter, userParameter, reportNameParameter);
        }
    
        public virtual ObjectResult<GetFieldDetails_Result> GetFieldDetails(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFieldDetails_Result>("GetFieldDetails", tableNameParameter);
        }
    
        public virtual int GetFilterFieldDetails(Nullable<int> reportID, string reportField)
        {
            var reportIDParameter = reportID.HasValue ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(int));
    
            var reportFieldParameter = reportField != null ?
                new ObjectParameter("ReportField", reportField) :
                new ObjectParameter("ReportField", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetFilterFieldDetails", reportIDParameter, reportFieldParameter);
        }
    
        public virtual int GetPendingTransactionByUser(Nullable<int> processGuidelineId, Nullable<int> userID)
        {
            var processGuidelineIdParameter = processGuidelineId.HasValue ?
                new ObjectParameter("ProcessGuidelineId", processGuidelineId) :
                new ObjectParameter("ProcessGuidelineId", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetPendingTransactionByUser", processGuidelineIdParameter, userIDParameter);
        }
    
        public virtual int GetProcessFlowByUser(Nullable<int> processGuidelineId, Nullable<int> userID, Nullable<int> refId)
        {
            var processGuidelineIdParameter = processGuidelineId.HasValue ?
                new ObjectParameter("ProcessGuidelineId", processGuidelineId) :
                new ObjectParameter("ProcessGuidelineId", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var refIdParameter = refId.HasValue ?
                new ObjectParameter("RefId", refId) :
                new ObjectParameter("RefId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetProcessFlowByUser", processGuidelineIdParameter, userIDParameter, refIdParameter);
        }
    
        public virtual ObjectResult<GetProcessTransactionByUser_Result> GetProcessTransactionByUser(Nullable<int> processGuidelineId, string userID)
        {
            var processGuidelineIdParameter = processGuidelineId.HasValue ?
                new ObjectParameter("ProcessGuidelineId", processGuidelineId) :
                new ObjectParameter("ProcessGuidelineId", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProcessTransactionByUser_Result>("GetProcessTransactionByUser", processGuidelineIdParameter, userIDParameter);
        }
    
        public virtual int UpdatePayment(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePayment", userIdParameter);
        }
    }
}
