//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatentISEntities : DbContext
    {
        public PatentISEntities()
            : base("name=PatentISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_draft_AnnexB1> tbl_draft_AnnexB1 { get; set; }
        public virtual DbSet<tbl_draft_AppAreas> tbl_draft_AppAreas { get; set; }
        public virtual DbSet<tbl_draft_applicants> tbl_draft_applicants { get; set; }
        public virtual DbSet<tbl_draft_comMode> tbl_draft_comMode { get; set; }
        public virtual DbSet<tbl_files_PatentRequest> tbl_files_PatentRequest { get; set; }
        public virtual DbSet<tbl_mst_ListItem> tbl_mst_ListItem { get; set; }
        public virtual DbSet<tbl_trx_AnnexureB1> tbl_trx_AnnexureB1 { get; set; }
        public virtual DbSet<tbl_trx_ApplicationAreas> tbl_trx_ApplicationAreas { get; set; }
        public virtual DbSet<tblAnnexureB1> tblAnnexureB1 { get; set; }
        public virtual DbSet<tblCommercialisationMode> tblCommercialisationMode { get; set; }
        public virtual DbSet<tbl_Trademark> tbl_Trademark { get; set; }
        public virtual DbSet<tbl_trx_Applicants> tbl_trx_Applicants { get; set; }
        public virtual DbSet<tbl_CR_Author> tbl_CR_Author { get; set; }
        public virtual DbSet<tbl_CR_Publish> tbl_CR_Publish { get; set; }
        public virtual DbSet<tblCoInventor> tblCoInventor { get; set; }
        public virtual DbSet<tbl_Copyright> tbl_Copyright { get; set; }
        public virtual DbSet<tbl_draft_IDFReq> tbl_draft_IDFReq { get; set; }
        public virtual DbSet<tbl_draft_Coinventor> tbl_draft_Coinventor { get; set; }
        public virtual DbSet<tbl_trx_CommercialisationMode> tbl_trx_CommercialisationMode { get; set; }
        public virtual DbSet<tbl_Trade_Applicantdetail> tbl_Trade_Applicantdetail { get; set; }
        public virtual DbSet<tblApplicants> tblApplicants { get; set; }
        public virtual DbSet<tbl_mst_filepath> tbl_mst_filepath { get; set; }
        public virtual DbSet<tbl_draft_Copyright> tbl_draft_Copyright { get; set; }
        public virtual DbSet<tbl_draft_CR_Author> tbl_draft_CR_Author { get; set; }
        public virtual DbSet<tbl_draft_Trade_Applicantdetail> tbl_draft_Trade_Applicantdetail { get; set; }
        public virtual DbSet<tbl_draft_Trademark> tbl_draft_Trademark { get; set; }
        public virtual DbSet<tbl_trx_Copyright> tbl_trx_Copyright { get; set; }
        public virtual DbSet<tbl_trx_CR_Author> tbl_trx_CR_Author { get; set; }
        public virtual DbSet<tbl_trx_CR_Publish> tbl_trx_CR_Publish { get; set; }
        public virtual DbSet<tbl_trx_Trade_Applicantdetail> tbl_trx_Trade_Applicantdetail { get; set; }
        public virtual DbSet<tbl_trx_Trademark> tbl_trx_Trademark { get; set; }
        public virtual DbSet<tbl_draft_CR_Publish> tbl_draft_CR_Publish { get; set; }
        public virtual DbSet<tblIDFRequest> tblIDFRequest { get; set; }
        public virtual DbSet<tbl_trx_IDFRequest> tbl_trx_IDFRequest { get; set; }
        public virtual DbSet<tbl_trx_CoInventor> tbl_trx_CoInventor { get; set; }
        public virtual DbSet<tblApplicationAreas> tblApplicationAreas { get; set; }
    }
}
