//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_CommercialisationMode
    {
        public long tranx_id { get; set; }
        public int VersionId { get; set; }
        public int Sno { get; set; }
        public long FileNo { get; set; }
        public int IndNo { get; set; }
        public string Category { get; set; }
        public string Mode { get; set; }
    }
}
