//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_Trademark
    {
        public long trx_id { get; set; }
        public int VersionId { get; set; }
        public long FileNo { get; set; }
        public string Category { get; set; }
        public string TMName { get; set; }
        public string Description { get; set; }
        public bool TMImage { get; set; }
        public string Language { get; set; }
        public string Class { get; set; }
        public string TMStatement { get; set; }
    }
}
