//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_CR_Publish
    {
        public long trx_id { get; set; }
        public int VersionId { get; set; }
        public Nullable<long> FileNo { get; set; }
        public Nullable<int> Sno { get; set; }
        public string PUName { get; set; }
        public string PUAddress { get; set; }
        public string PUNationality { get; set; }
        public Nullable<int> Year { get; set; }
        public string Country { get; set; }
    }
}
