//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_ListItem
    {
        public long tranx_id { get; set; }
        public string Category { get; set; }
        public string ItemText { get; set; }
        public string ItemValue { get; set; }
        public string Grouping { get; set; }
        public string Description { get; set; }
    }
}
