//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CR_Author
    {
        public long trx_id { get; set; }
        public long FileNo { get; set; }
        public int SNo { get; set; }
        public string AUName { get; set; }
        public string AUAddress { get; set; }
        public string AUNationality { get; set; }
        public Nullable<bool> isDeceased { get; set; }
        public Nullable<System.DateTime> deceasedDt { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
    }
}
