//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgencySalary
    {
        public int AgencySalaryId { get; set; }
        public string PaymentNo { get; set; }
        public Nullable<System.DateTime> PaymentMonthYear { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
        public Nullable<int> TotalEmployees { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> Crtd_TS { get; set; }
        public Nullable<int> Crtd_UserId { get; set; }
        public Nullable<int> LastupdatedUserid { get; set; }
        public Nullable<System.DateTime> Lastupdate_TS { get; set; }
        public Nullable<int> SqquenceNo { get; set; }
        public string MonthYearStr { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<decimal> NetPayable { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public Nullable<int> CheckListVerified_By { get; set; }
        public Nullable<bool> Pmt_f { get; set; }
        public Nullable<decimal> GST { get; set; }
    }
}
