//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnnexureB1
    {
        public long tranx_id { get; set; }
        public long FileNo { get; set; }
        public string BriefDescription { get; set; }
        public string DevelopmentStage { get; set; }
        public string OtherInfo { get; set; }
        public Nullable<bool> L1Search { get; set; }
        public string Tool { get; set; }
        public string Party { get; set; }
        public string Outcome { get; set; }
        public string Comments { get; set; }
    }
}
