//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgencyVerifiedSalary
    {
        public int VerifiedSalaryId { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> Netsalary { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> Crtd_TS { get; set; }
        public Nullable<int> Crtd_UserId { get; set; }
        public string MonthYear { get; set; }
        public Nullable<int> AgencySalaryId { get; set; }
    }
}
