//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommonHeads
    {
        public int HeadId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Head { get; set; }
        public string Code { get; set; }
    }
}
