//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistributionOHPDetails
    {
        public int Id { get; set; }
        public Nullable<int> DistributionId { get; set; }
        public Nullable<int> DistributionOHId { get; set; }
        public string OverheadType { get; set; }
        public Nullable<int> OverheadTypeId { get; set; }
        public Nullable<decimal> OverheadAmount { get; set; }
        public Nullable<int> OverheadProjectId { get; set; }
        public Nullable<int> OverheadBankId { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Pmt_f { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> ReturnReceiptId { get; set; }
    }
}
