//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDynamicFilter
    {
        public Nullable<int> ReportID { get; set; }
        public string ReportField { get; set; }
        public string FieldType { get; set; }
        public string RefTable { get; set; }
        public string RefField { get; set; }
        public bool IsRange { get; set; }
    }
}
