//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForeignRemittance
    {
        public int ForeignRemitId { get; set; }
        public Nullable<int> Beneficiary { get; set; }
        public Nullable<System.DateTime> ForeignRemitanceDate { get; set; }
        public string ForeignRemitNumber { get; set; }
        public Nullable<int> SourceReferenceNumber { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
        public string PONumber { get; set; }
        public Nullable<int> TypeofPayment { get; set; }
        public Nullable<int> PaymentBank { get; set; }
        public Nullable<int> PortfolioName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountNumberForDebitCharges { get; set; }
        public string ForgnCurrncyEqualtoINR { get; set; }
        public Nullable<decimal> RemittanceAmount { get; set; }
        public string RemittanceAmountinWords { get; set; }
        public Nullable<int> RemittanceCurrency { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string IntermediaryBank { get; set; }
        public string IntermediaryBankAddress { get; set; }
        public string IntermediaryBankCodeNumber { get; set; }
        public Nullable<int> ForeignBankChargesType { get; set; }
        public string ShipmentDetails { get; set; }
        public Nullable<int> PurposeofRemittance { get; set; }
        public string GoodsDescription { get; set; }
        public string HSClassificationCode { get; set; }
        public string ImportLicenseDetails { get; set; }
        public string SpecialReferenceNumber { get; set; }
        public string RateorContractBookedDetails { get; set; }
        public Nullable<int> ExpensesHead { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<int> Source { get; set; }
        public string Remarks { get; set; }
        public string CommentstoBank { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
        public Nullable<int> CheckListVerifiedBy { get; set; }
        public Nullable<int> CommitmentId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> DebitChargesAccountHeadId { get; set; }
        public Nullable<System.DateTime> ExpectedDateofDespatch { get; set; }
        public string PortofDespatch { get; set; }
        public string DestinationPort { get; set; }
        public Nullable<int> CountryofOriginofGoods { get; set; }
        public string ShippingCompany { get; set; }
        public Nullable<System.DateTime> Paymentdate { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<decimal> FXRate { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> BillCommission { get; set; }
        public Nullable<decimal> BillCGST { get; set; }
        public Nullable<decimal> BillSGST { get; set; }
        public Nullable<decimal> TotalAmountDebitedtoProject { get; set; }
        public string BillofEntryNo { get; set; }
        public Nullable<System.DateTime> BillofEntryDate { get; set; }
        public Nullable<decimal> CustomsDuty { get; set; }
        public Nullable<decimal> DemurrageCharges { get; set; }
        public Nullable<decimal> AirportAuthorityDuty { get; set; }
        public Nullable<decimal> ClearingCharges { get; set; }
        public Nullable<decimal> Othersifany { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string FOTTReferenceNumber { get; set; }
        public string UserReferenceNumber { get; set; }
        public string RemittanceCurrencyCode { get; set; }
    }
}
