//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTMonthlySplitup
    {
        public int GSTMonthlySplitupId { get; set; }
        public Nullable<int> GSTOffsetid { get; set; }
        public Nullable<decimal> IGSTOutput { get; set; }
        public Nullable<decimal> IGSTInput { get; set; }
        public Nullable<decimal> CGSTOutput { get; set; }
        public Nullable<decimal> CGSTInput { get; set; }
        public Nullable<decimal> SGSTOutput { get; set; }
        public Nullable<decimal> SGSTInput { get; set; }
        public Nullable<decimal> CreditAdjInIGST { get; set; }
        public Nullable<decimal> CreditAdjInSGST { get; set; }
        public Nullable<decimal> CreditAdjInCGST { get; set; }
        public Nullable<decimal> IGSTBalanceForAdj { get; set; }
        public Nullable<decimal> CGSTBalanceForAdj { get; set; }
        public Nullable<decimal> SGSTBalanceForAdj { get; set; }
        public Nullable<decimal> CGSTAdjInIGST { get; set; }
        public Nullable<decimal> SGSTAdjInIGST { get; set; }
        public Nullable<decimal> AdjInCGST { get; set; }
        public Nullable<decimal> AdjInSGST { get; set; }
        public Nullable<decimal> PayableIGST { get; set; }
        public Nullable<decimal> PayableCGST { get; set; }
        public Nullable<decimal> PayableSGST { get; set; }
        public Nullable<decimal> TDSIGST { get; set; }
        public Nullable<decimal> TDSCGST { get; set; }
        public Nullable<decimal> TDSSGST { get; set; }
        public Nullable<decimal> AdjPayableIGST { get; set; }
        public Nullable<decimal> AdjPayableCGST { get; set; }
        public Nullable<decimal> AdjPayableSGST { get; set; }
        public Nullable<decimal> NetPayableInIGST { get; set; }
        public Nullable<decimal> NetPayableInCGST { get; set; }
        public Nullable<decimal> NetPayableInSGST { get; set; }
        public Nullable<decimal> BalanceTDSinIGST { get; set; }
        public Nullable<decimal> BalanceTDSinCGST { get; set; }
        public Nullable<decimal> BalanceTDSinSGST { get; set; }
        public Nullable<decimal> TotalGSTPayable { get; set; }
        public Nullable<decimal> TotalTDS { get; set; }
        public Nullable<int> UPDT_By { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string Status { get; set; }
    }
}
