//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTOffsetdetails
    {
        public int GSTOffsetdetailsid { get; set; }
        public Nullable<int> GSTOffsetid { get; set; }
        public Nullable<int> BOATransactionId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionType { get; set; }
        public string Remarks { get; set; }
    }
}
