//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLCDraftDetails
    {
        public int Id { get; set; }
        public string DraftLCNumber { get; set; }
        public string LCReferenceNumber { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string PONumber { get; set; }
        public Nullable<int> CommitmentId { get; set; }
        public Nullable<int> IssuingBank { get; set; }
        public string IssuingBankAccountNumber { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> RemittanceCurrency { get; set; }
        public Nullable<decimal> RemittanceAmount { get; set; }
        public string PlaceofExpiry { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> CreditAvailableBank { get; set; }
        public Nullable<int> CreditAvailableBy { get; set; }
        public string CreditAvailableFor { get; set; }
        public string CreditAvailableTenor { get; set; }
        public string AdvisingBank { get; set; }
        public string AdvisingBankBranch { get; set; }
        public string AdvisingBankAddress { get; set; }
        public string AdvisingBankCity { get; set; }
        public string AdvisingBankState { get; set; }
        public Nullable<int> AdvisingBankCountry { get; set; }
        public string BankPostalCode { get; set; }
        public string AdvisingBankSwiftorIFSC { get; set; }
        public string DraweeBank { get; set; }
        public string Beneficiary { get; set; }
        public string BeneficiaryAddress { get; set; }
        public string BeneficiaryCity { get; set; }
        public string BeneficiaryState { get; set; }
        public Nullable<int> BeneficiaryCountry { get; set; }
        public string BeneficiaryPostalCode { get; set; }
        public Nullable<int> PartialShipmentOption { get; set; }
        public Nullable<int> TransShipmentOption { get; set; }
        public string PortorAirportofDeparture { get; set; }
        public string PortorAirportofDestination { get; set; }
        public Nullable<System.DateTime> DateofShipment { get; set; }
        public string DescriptionofGoodsandService { get; set; }
        public string ProformaInvoiceNumber { get; set; }
        public Nullable<System.DateTime> ProformaInvoiceDate { get; set; }
        public Nullable<int> CountryofOrigin { get; set; }
        public string InsuranceCoverageDetails { get; set; }
        public string InsurancePolicyNumber { get; set; }
        public Nullable<System.DateTime> InsurancePolicyDate { get; set; }
        public Nullable<int> TradeINCOTerms { get; set; }
        public Nullable<decimal> ChargesAmount { get; set; }
        public string PresentationPeriod { get; set; }
        public string DocumentsRequired { get; set; }
        public Nullable<int> ModeofDispatch { get; set; }
        public string DocumentInfoDetails { get; set; }
        public string Remarks { get; set; }
        public string BankReferenceNumber { get; set; }
        public string EstablishmentRemarks { get; set; }
        public string EstablishedLCNumber { get; set; }
        public Nullable<decimal> EstablishmentBankCharges { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
        public Nullable<int> CheckListVerifiedBy { get; set; }
        public Nullable<int> SourceReferenceNumber { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
        public Nullable<int> Source { get; set; }
        public string DocumentActualName { get; set; }
        public string DocPath { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> FinancialYear { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string RemittanceAmountinWords { get; set; }
    }
}
