//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManDayDetails
    {
        public int ManDayDetailsId { get; set; }
        public Nullable<int> ManDayId { get; set; }
        public Nullable<System.DateTime> MonthYear { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string StaffName { get; set; }
        public string Department { get; set; }
        public Nullable<int> NoofDays { get; set; }
        public Nullable<decimal> AmountPerDay { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> ModeOfPayment { get; set; }
        public Nullable<int> UPDT_By { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string Status { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string AccountNo { get; set; }
        public string IFSC { get; set; }
    }
}
