//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectDirectTransfer
    {
        public int ProjectTransferId { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string TransferNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> DebitProjectId { get; set; }
        public Nullable<int> CreditProjectId { get; set; }
        public string DocumentActualName { get; set; }
        public string DocumentName { get; set; }
        public string DebitProject { get; set; }
        public string CreditProject { get; set; }
        public Nullable<int> DebitBank { get; set; }
        public Nullable<int> CreditBank { get; set; }
        public Nullable<int> ReceiptId { get; set; }
    }
}
