//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPCFDistribution
    {
        public int Id { get; set; }
        public Nullable<int> TypeofPayment { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string ReferenceNumber { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string Status { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> ReturnReceiptId { get; set; }
    }
}
