//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectOBDetail
    {
        public int OBDetailId { get; set; }
        public Nullable<int> OBId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> HeadId { get; set; }
        public Nullable<decimal> OpeningExp { get; set; }
        public Nullable<System.DateTime> Crt_TS { get; set; }
    }
}
