//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceiptClaimsdetail
    {
        public int ReceiptClaimsdetailId { get; set; }
        public Nullable<int> ReceiptClaimsId { get; set; }
        public Nullable<int> InstituteClaimsId { get; set; }
        public Nullable<int> ModeOfReceipt { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> ChequeValue { get; set; }
        public string BankRefNo { get; set; }
        public Nullable<System.DateTime> BankDate { get; set; }
        public Nullable<decimal> BankValue { get; set; }
        public Nullable<int> UPDT_By { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string Status { get; set; }
        public Nullable<int> ReturnReceiptId { get; set; }
        public Nullable<int> BankHeadId { get; set; }
    }
}
