//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ApprovalProcessFlowDetails
    {
        public int FunctionId { get; set; }
        public Nullable<int> ProcessTransactionId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ApproverLevel { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<int> ProcessSeqNumber { get; set; }
        public Nullable<int> CurrentApproverId { get; set; }
        public string ActionStatus { get; set; }
        public Nullable<System.DateTime> TransactionTS { get; set; }
        public string ActionLink { get; set; }
        public string FunctionName { get; set; }
        public string ID { get; set; }
        public string RefNumber { get; set; }
    }
}
