//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CashBookPayment
    {
        public int BOAPaymentDetailId { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PayeeBank { get; set; }
        public Nullable<int> BOAId { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> BankHeadID { get; set; }
        public string PayeeName { get; set; }
        public Nullable<int> PayeeId { get; set; }
        public string VoucherPayee { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public string RefNumber { get; set; }
        public Nullable<decimal> BOAValue { get; set; }
    }
}
