//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Fellowship
    {
        public int ID { get; set; }
        public string PaymentNo { get; set; }
        public string PaymentMonth { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string FellowshipSalaryNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Name { get; set; }
        public string PayeeCategory { get; set; }
    }
}
