//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectTransactionReport
    {
        public Nullable<int> ProjectId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateOfTransaction { get; set; }
        public string RefNo { get; set; }
        public string TransType { get; set; }
        public string Code { get; set; }
        public string FunctionName { get; set; }
        public string Category { get; set; }
        public string CommitmentNumber { get; set; }
    }
}
