//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SubLedger
    {
        public Nullable<int> ID { get; set; }
        public int Type { get; set; }
        public Nullable<int> BOATransactionId { get; set; }
        public string TypeName { get; set; }
        public string Name { get; set; }
        public string PAN { get; set; }
    }
}
