//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VoucherBatch
    {
        public int BOADraftId { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string TempVoucherNumber { get; set; }
        public string BOADraftStatus { get; set; }
        public string PayeeType { get; set; }
        public string PayeeName { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionType { get; set; }
        public string PaymentPayeeStatus { get; set; }
    }
}
