//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAdhocEmployeeCategory
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public Nullable<int> SalaryType { get; set; }
        public string SalaryRef { get; set; }
    }
}
