//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAppointmentProject
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string MeetingID { get; set; }
        public string DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public string ProjectType { get; set; }
        public bool PartTime { get; set; }
        public string ProjectNo { get; set; }
        public string PICode { get; set; }
        public string PIName { get; set; }
        public string DepartmentCode { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<System.DateTime> ProjectRelieveDate { get; set; }
        public Nullable<System.DateTime> RelievedOn { get; set; }
        public string RelievedBy { get; set; }
        public string Remarks { get; set; }
    }
}
