//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPaytype
    {
        public int id { get; set; }
        public string ptype { get; set; }
        public Nullable<bool> additionalPay { get; set; }
        public string reportText { get; set; }
        public Nullable<bool> deductible { get; set; }
    }
}
