//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSalaryDetails
    {
        public string EmployeeId { get; set; }
        public int OrderID { get; set; }
        public string OrderType { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal HRA { get; set; }
        public decimal Bonus { get; set; }
        public decimal SpecialAllowance { get; set; }
        public decimal GrossSalary { get; set; }
        public decimal EmployeePF { get; set; }
        public decimal EmployeeESIC { get; set; }
        public decimal ProfessionalTax { get; set; }
        public decimal NetSalary { get; set; }
        public decimal EmployerPF { get; set; }
        public decimal EmployerESIC { get; set; }
        public decimal Insurance { get; set; }
        public decimal TotalContribution { get; set; }
        public decimal GrossTotal { get; set; }
        public decimal AgencyFee { get; set; }
        public decimal ServiceTax { get; set; }
        public decimal TotalSalary { get; set; }
    }
}
