//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSalaryMaster
    {
        public int SalMonth { get; set; }
        public int SalYear { get; set; }
        public string Fileno { get; set; }
        public string SalaryID { get; set; }
        public bool Used { get; set; }
    }
}
