//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTapalDetails
    {
        public Nullable<int> TapalType { get; set; }
        public string SenderDetail { get; set; }
        public Nullable<int> PIName { get; set; }
        public Nullable<int> ProjectNumber { get; set; }
        public Nullable<bool> IsInward { get; set; }
        public string CodeValDetail { get; set; }
    }
}
